modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="betterwaystonesmenu"
version="${file.jarVersion}"
displayName="BetterWaystonesMenu"
logoFile="betterwaystonesmenu-icon.png"
authors="Loxoz, BluSpring"
description='''
Enhances the Waystones' mod selection menu
'''

[[dependencies.betterwaystonesmenu]]
   modId="forge"
   mandatory=true
   versionRange="[47,)"
   ordering="NONE"
   side="BOTH"
[[dependencies.betterwaystonesmenu]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.20,1.21)"
   ordering="NONE"
   side="BOTH"
[[dependencies.betterwaystonesmenu]]
    modId="waystones"
    mandatory=true
    versionRange="[14.1.3,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.betterwaystonesmenu]]
    modId="balm"
    mandatory=true
    versionRange="[7.2.2,)"
    ordering="NONE"
    side="BOTH"
